### PR TITLE
Fix crash when renaming or deleting a file

### LINKED ISSUE #48: Watcher Crash on renamed/removed files
It seems that the watcher does crash when files get removed after they were watched.

### PR DESCRIPTION
**Pull request by adamuso**
Fixed a crash when file was renamed or deleted.

Crash dump:
```ts
node:fs:1536
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '/home/adam/Documents/git/adamuso/test-project/scripts/src/Test.ts'
    at Object.statSync (node:fs:1536:3)
    at ignored (/home/adam/Documents/git/adamuso/ts2gd/js/project/project.js:260:71)
    at matchPatterns (/home/adam/Documents/git/adamuso/ts2gd/node_modules/anymatch/index.js:62:18)
    at FSWatcher._userIgnored (/home/adam/Documents/git/adamuso/ts2gd/node_modules/anymatch/index.js:96:14)
    at FSWatcher._isIgnored (/home/adam/Documents/git/adamuso/ts2gd/node_modules/chokidar/index.js:779:15)
    at FSWatcher._remove (/home/adam/Documents/git/adamuso/ts2gd/node_modules/chokidar/index.js:895:27)
    at listener (/home/adam/Documents/git/adamuso/ts2gd/node_modules/chokidar/lib/nodefs-handler.js:381:18) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/adam/Documents/git/adamuso/test-project/scripts/src/Test.ts'
}
```

closes #48

### CODE REVIEW

File: project/project.ts [hunk 1]
```diff
@@ -356,6 +356,10 @@ export const makeTsGdProject = async (
           // Chokidar is inconsistent about whether it passes in stats or not -
```
Comment (ksjogo) [inline project/project.ts:356]: Should this comment then be moved down to stay with the fs.statSync?

File: project/project.ts [hunk 2]
```diff
@@ -356,6 +356,10 @@ export const makeTsGdProject = async (
...
           // sometimes it does and sometimes it doesn't.
 
+          if (!fs.existsSync(path)) {
```
Comment (ksjogo) [inline project/project.ts:359]: Do we need to additionally handle clean up somehow? E.g. some unlink event handler?
I think we might have a reference to previously exisiting files stored in the onAdd handler.

File: project/project.ts (hunk 1 above)
Comment (adamuso) [reply project/project.ts]: Moved.

File: project/project.ts (hunk 2 above)
Comment (adamuso) [reply project/project.ts]: You are right, there is `unlink` handler which should be invoked. I changed it to not loading `stats` when file does not exist.

File: project/project.ts [hunk 3]
```diff
@@ -390,7 +392,7 @@ const shouldIncludePath = (path: string, stats: fs.Stats): boolean => {
     return false
   }
 
-  if (stats.isDirectory()) {
+  if (stats && stats.isDirectory()) {
```
Comment (ksjogo) [inline project/project.ts:395]: I think `stats?.isDirectory()` should do the same and be the more modern style. But doesn't really matter.

File: project/project.ts [hunk 4]
```diff
@@ -369,7 +371,7 @@ export const makeTsGdProject = async (
   return new TsGdProjectClass(watcher, initialFiles, program, ts2gdJson, args)
 }
 
-const shouldIncludePath = (path: string, stats: fs.Stats): boolean => {
+const shouldIncludePath = (path: string, stats?: fs.Stats): boolean => {
```
Comment (ksjogo) [inline project/project.ts:374]: Just wondering when this is invoked?
Is this invoked for a deleted file on unlink? 
Or when would we have non-existing files here?

Comment (johnfn) [reply project/project.ts:374]: chokidar will call this (indirectly) to see if it should care about certain files or not. It probably gets called when you delete/remove a file because it's checking to see if it should emit events about them.

**Comment by johnfn** [comment]
Awesome, thank you!

File: project/project.ts (hunk 3 above)
Comment (adamuso) [reply project/project.ts:395]: Yeah, I'm using TypeScript for long time (form versions 2.x) and I have still habits of using old style code. Mainly because I work on codespaces were we still have old TS versions and not everything is supported 😛
